/*export const PIPELINE = "PIPELINE";
export const DOALL = "DOALL";
export const GEOMETRICDECOMPOSITION = "GEOMETRICDECOMPOSITION";
export const TASKPARALLELISM = "TASKPARALLELISM"
export const FORK = "FORK"
export const WORKER = "WORKER"
export const BARRIER = "BARRIER"*/
const WORKER = "WORKER";
const BARRIER = "BARRIER";
const CON_BARRIER = "CON_BARRIER";
const NONCON_BARRIER = "NONCON_BARRIER";
const PIPELINE = "Pipeline";
const DOALL = "Do-All";
const GEOMETRICDECOMPOSITION = "Geometric Decomposition";
const TASKPARALLELISM = "Task Parallelism"
const FORK = "FORK";
const PATTERNBORDERCOLOR = "#be1d02";
const NORMALFILLCOLOR = "white";
const EVALUATIONFILLCOLOR = "#F5BDA2"; 
const EVALUATEDNODEBORDERCOLOR = "#F5BDA2";
const NORMALBORDERCOLOR = "#A4A4A4";
const FORKFILLCOLOR = "#0b8021";
const WORKERFILLCOLOR = "#0ea82b";
const CON_BARRIERFILLCOLOR = "#08e431";
const NONCON_BARRIERFILLCOLOR = "#707070";

 module.exports = {
    FORK,WORKER,BARRIER,PIPELINE,DOALL,GEOMETRICDECOMPOSITION,TASKPARALLELISM,
    PATTERNBORDERCOLOR,
    NORMALBORDERCOLOR,
    NORMALFILLCOLOR,
    EVALUATIONFILLCOLOR,
    EVALUATEDNODEBORDERCOLOR,
    FORKFILLCOLOR,
    WORKERFILLCOLOR,
    CON_BARRIERFILLCOLOR, NONCON_BARRIERFILLCOLOR,
    CON_BARRIER,NONCON_BARRIER
  }
